Repository Photinia-Milk/Dolo-Front-End, pull requests merged in 2020-07, with the labels that each got.

#4 Feature: a better login view
  package.json
  public/icons.png
  public/login-bg.jpg
  public/login-cloud.png
  src/config/axios.js
  src/main.js
  src/views/Loading.vue
  src/views/Login.vue
Labels: enhancement

#5 Feature: better select course view
  src/assets/logo.png
  src/components/Loading.vue
  src/router/index.js
  src/views/login/Login.vue
  src/views/student/Student.vue
  src/views/student/components/CourseSelect.vue
  src/views/student/components/DropCourse.vue
  src/views/student/components/NavBarStudent.vue
  src/views/student/components/SearchBox.vue
  src/views/student/components/SelectCourse.vue
  src/views/student/components/navbar/NavBarStudent.vue
  src/views/student/components/select/CourseSelect.vue
  src/views/student/components/select/components/CourseTable.vue
  src/views/student/components/select/components/SchoolArticles.vue
  src/views/student/components/select/components/SearchBox.vue
  src/views/teacher/TeacherMain.vue
  src/views/teacher/components/navbar/NavBarTeacher.vue
  src/views/teacher/components/publish/PublishCourse.vue
Labels: enhancement

#8 Branch new pages and combination
  .gitignore
  package-lock.json
  package.json
  src/App.vue
  src/api/api.js
  src/api/index.js
  src/assets/Login/login2.jpeg
  src/assets/css/login.css
  src/main.js
  src/router/index.js
  src/static/css/error-mask.css
  src/static/js/clickoutside.js
  src/static/js/cloneObject.js
  src/static/js/cookie.js
  src/static/js/date.js
  src/static/js/meteor.exec.js
  src/views/login/Login2.vue
  src/views/student/Student.vue
  src/views/student/components/CourseSelect/components/CourseAll.vue
  src/views/student/components/CourseSelect/courseSelect.vue
  src/views/student/components/courseTable/courseTable.vue
  src/views/student/components/home/components/SchoolArticles.vue
  src/views/student/components/home/home.vue
  src/views/student/components/navbar/NavBarStudent.vue
  src/views/student/components/select/CourseSelect.vue
  src/views/student/components/select/components/CourseTable.vue
  src/views/student/components/select/components/SearchBox.vue
  src/views/teacher/components/navbar/NavBarTeacher.vue
  src/views/teacher/components/publish/PublishCourse.vue
Labels: documentation, enhancement

#12 Feat integration
  .gitignore
  coverage/Front-end/babel.config.js.html
  coverage/Front-end/coverage/block-navigation.js.html
  coverage/Front-end/coverage/index.html
  coverage/Front-end/coverage/prettify.js.html
  coverage/Front-end/coverage/sorter.js.html
  coverage/Front-end/dist/js/chunk-vendors.caf0425e.js.html
  coverage/Front-end/dist/js/index.html
  coverage/Front-end/index.html
  coverage/index.html
  src/api/api.js
  src/config/axios.js
  src/views/student/components/CourseSelect/components/CourseAll.vue
Labels: bug, enhancement
